### ISSUE TITLE
Explicitly placing every area

### ISSUE THREAD

**Issue by oliverjam** [bobbysebolao/learn-css-grid#3]
Grid is super powerful, which can sometimes be dangerous. It's easy to go full print-designer and explicitly place every single element on the grid. But this kind of breaks the way layout on the web should work. Ideally the elements just flow into place, no matter how many there are. If we have to add specific numbered classes to each that makes it much more difficult to support arbitrary content.

It is possible to get pretty much the same layout without explicitly placing anything but the sidebar at the end: https://codepen.io/oliverjam/pen/dyoJGQg?editors=1100

You let the grid algorithm place extra children within the first 4 columns, and explicitly tell the sidebar to take up the final column.

**Comment by bobbysebolao** [comment]
Brilliant, thank you for showing me this! I've removed `grid-template-areas` from the solution 👍
